default: true

# Entspannte Regeln für Entwickler-Dokumentation
MD013: false  # Line length - zu restriktiv für technische Docs
MD033: false  # Inline HTML - manchmal nützlich für Diagramme/Badges
MD041: false  # First line heading - README.md hat oft Badges

# Erlaubte Heading-Duplikate (wichtig für API-Docs)
MD024:
  siblings_only: true

# Lockere Listen-Indentation
MD007:
  indent: 2

# Code-Blöcke brauchen Language-Tags
MD040: true
MD046:
  style: fenced
