import kotlinx.browser.window
import kotlinx.coroutines.await
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class AppConfig(
    val apiBaseUrl: String
)

suspend fun loadAppConfig(): AppConfig {
    return try {
        // Fetch config.json generated by Caddy templates
        val response = window.fetch("/config.json").await()
        if (!response.ok) {
            console.warn("[Config] Failed to load config.json, falling back to defaults")
            return AppConfig(apiBaseUrl = window.location.origin)
        }
        val text = response.text().await()
        Json.decodeFromString(AppConfig.serializer(), text)
    } catch (e: dynamic) {
        console.error("[Config] Error loading config:", e)
        // Fallback for local development if file is missing
        AppConfig(apiBaseUrl = "http://localhost:8081")
    }
}
