package at.mocode.core.domain.model

import kotlinx.serialization.Serializable

/**
 * Defines the source of a data record.
 */
@Serializable
enum class DatenQuelleE {
    MANUELL,           // Manually entered
    IMPORT_ZNS,        // Imported from OEPS ZNS data
    SYSTEM_GENERATED   // Generated by the system itself
}

/**
 * Defines the gender of a horse.
 */
@Serializable
enum class PferdeGeschlechtE {
    HENGST,     // Male, not castrated
    STUTE,      // Female
    WALLACH     // Male, castrated
}

/**
 * Person gender enumeration
 */
@Serializable
enum class GeschlechtE { M, W, D, UNBEKANNT }

/**
 * Defines the different equestrian disciplines (Sparten).
 * This enum is a central part of the Ubiquitous Language.
 */
@Serializable
enum class SparteE {
    DRESSUR,           // Dressurreiten
    SPRINGEN,          // Springreiten
    VIELSEITIGKEIT,    // Vielseitigkeitsreiten
    FAHREN,            // Fahrsport
    VOLTIGIEREN,       // Voltigieren
    WESTERN,           // Westernreiten
    DISTANZ,           // Distanzreiten
    PARA_DRESSUR,      // Para-Dressur
    ISLAND;            // Islandpferde
}

/**
 * Venue/place type enumeration
 */
@Serializable
enum class PlatzTypE { AUSTRAGUNG, VORBEREITUNG, LONGIEREN, SONSTIGES }

/**
 * User role enumeration for member management
 */
@Serializable
enum class RolleE {
    ADMIN,              // System administrator
    VEREINS_ADMIN,      // Club administrator
    FUNKTIONAER,        // Official/functionary
    REITER,             // Rider
    TRAINER,            // Trainer
    RICHTER,            // Judge
    TIERARZT,           // Veterinarian
    ZUSCHAUER,          // Spectator
    GAST                // Guest
}

/**
 * Permission enumeration for access control
 */
@Serializable
enum class BerechtigungE {
    // Person management
    PERSON_READ,
    PERSON_CREATE,
    PERSON_UPDATE,
    PERSON_DELETE,

    // Club management
    VEREIN_READ,
    VEREIN_CREATE,
    VEREIN_UPDATE,
    VEREIN_DELETE,

    // Event management
    VERANSTALTUNG_READ,
    VERANSTALTUNG_CREATE,
    VERANSTALTUNG_UPDATE,
    VERANSTALTUNG_DELETE,

    // Horse management
    PFERD_READ,
    PFERD_CREATE,
    PFERD_UPDATE,
    PFERD_DELETE,

    // Master data management
    STAMMDATEN_READ,
    STAMMDATEN_UPDATE,

    // System administration
    SYSTEM_ADMIN,
    BENUTZER_VERWALTEN,
    ROLLEN_VERWALTEN
}
