package at.mocode.enums

import kotlinx.serialization.Serializable

@Serializable
enum class RegelwerkTypE { OETO, FEI, SONSTIGE }

@Serializable
enum class DatenQuelleE { OEPS_ZNS, MANUELL }

@Serializable
enum class VerbandE { OEPS, FEI, SONSTIGE }

@Serializable
enum class CupSerieTypE { CUP_SERIE }


@Serializable
enum class LizenzKategorieE { REITERLIZENZ, FAHRERLIZENZ, STARTKARTE }
@Serializable
enum class LizenzTypE { REITER, FAHRER, VOLTIGIERER, WESTERN, WORKING_EQUITATION, POLO, STARTKARTE_ALLG, STARTKARTE_VOLTIGIEREN, STARTKARTE_WESTERN, STARTKARTE_ISLAND, STARTKARTE_FAHREN_JUGEND, STARTKARTE_HORSEBALL, STARTKARTE_POLO, PARAEQUESTRIAN, SONSTIGE }


@Serializable
enum class SportfachStammdatenTypE { DRESSURAUFGABE, WERTUNGSVERFAHREN_SPRINGEN, WERTUNGSVERFAHREN_DRESSUR, BEWERBSKLASSE, BEWERBSKATEGORIE_OETO }

@Serializable
enum class PruefungsViereckE { VIERECK_20X40, VIERECK_20X60 }

@Serializable
enum class RichtverfahrenModusE { GM, GT }

@Serializable
enum class ArtDesStechensE { EINFACHES_STECHEN }

@Serializable
enum class PferdeGeschlechtE {
    HENGST, STUTE, WALLACH, UNBEKANNT
}

@Serializable
enum class EventStatusE { IN_PLANUNG, AKTIV, BEENDET }

@Serializable
enum class NennungsArtE {
    ONLINE_PORTAL, EZNS_OEPS, EMAIL, TELEFON, FAX, VOR_ORT
}

@Serializable
enum class VeranstalterTypE { VEREIN, FIRMA, PRIVATPERSON, SONSTIGE, UNBEKANNT }
@Serializable
enum class PlatzTypE { AUSTRAGUNG, VORBEREITUNG, LONGIEREN, SONSTIGES }

@Serializable
enum class SparteE { DRESSUR, SPRINGEN, VIELSEITIGKEIT, FAHREN, VOLTIGIEREN, WESTERN, DISTANZ, ISLAND, PFERDESPORT_SPIEL, BASIS, KOMBINIERT, SONSTIGES }

@Serializable
enum class BewerbStatus { GEPLANT, OFFEN_FUER_NENNUNG, GESCHLOSSEN_FUER_NENNUNG, LAEUFT, ABGESCHLOSSEN, ABGESAGT }
@Serializable
enum class Bedingungstyp { LIZENZ_REITER, LIZENZ_FAHRER, ALTER_PFERD, ALTER_REITER, RASSE_PFERD, GESCHLECHT_PFERD, GESCHLECHT_REITER, STARTKARTE, SONSTIGES }
@Serializable
enum class BeginnzeitTypE { FIX_UM, NACH_BEWERB, CA_UM, ANSCHLIESSEND }
@Serializable
enum class Operator { GLEICH, UNGLEICH, MINDESTENS, MAXIMAL, ZWISCHEN, IN_LISTE, NICHT_IN_LISTE }
@Serializable
enum class FunktionaerRolle { RICHTER, PARCOURSBAUER, PARCOURSBAU_ASSISTENT, TECHN_DELEGIERTER, TURNIERBEAUFTRAGTER, STEWARD, ZEITNEHMER, SCHREIBER, VERANSTALTER_KONTAKT, TURNIERLEITER, HELFER, SONSTIGE }

@Serializable
enum class RichterPositionE { C, E, H, M, B, VORSITZ, SEITENRICHTER, SONSTIGE }
@Serializable
enum class GeschlechtE { M, W, D, UNBEKANNT }
@Serializable
enum class GeschlechtPferdE { HENGST, STUTE, WALLACH, UNBEKANNT }

// Pruefungsaufgabe related enums
@Serializable
enum class PruefungsaufgabeNationE { NATIONAL, FEI, SONSTIGE }

@Serializable
enum class PruefungsaufgabeRichtverfahrenModusE { GM, GT, NICHT_SPEZIFIZIERT }

@Serializable
enum class PruefungsaufgabeViereckE { VIERECK_20X40, VIERECK_20X60, ANDERE, UNBEKANNT }

// Horse related enums
@Serializable
enum class PferdeFarbeE {
    BRAUN, FUCHS, RAPPE, SCHIMMEL, SCHECKE, FALBE, ISABELL, CREMELLO, PERLINO,
    SMOKY_CREAM, CHAMPAGNE, SILVER, DUN, BUCKSKIN, PALOMINO, GRULLA, RED_DUN,
    BAY_DUN, ROAN, GREY, CHESTNUT, BLACK, BAY, SORREL, PINTO, PAINT, APPALOOSA,
    SONSTIGE, UNBEKANNT
}

@Serializable
enum class PferdeRasseKategorieE {
    WARMBLUT, VOLLBLUT, KALTBLUT, PONY, KLEINPFERD, HAFLINGER, NORIKER,
    ARABER, FRIESE, ISLAENDER, QUARTER_HORSE, PAINT_HORSE, APPALOOSA,
    SHETLAND_PONY, WELSH_PONY, CONNEMARA, NEW_FOREST, DARTMOOR,
    SONSTIGE, UNBEKANNT
}

// Competition and licensing enums
@Serializable
enum class LeistungsklasseE {
    E, A, L, M, S, INTER_I, INTER_II, GRAND_PRIX, KINDER, JUGEND,
    JUNGE_REITER, U25, AMATEUR, PROFI, SONSTIGE
}

@Serializable
enum class QualifikationsStatusE {
    GUELTIG, ABGELAUFEN, SUSPENDIERT, WIDERRUFEN, IN_BEARBEITUNG, BEANTRAGT
}

@Serializable
enum class TurnierKategorieE {
    CDN_A, CDN_B, CDN_C, CDI_1STERN, CDI_2STERN, CDI_3STERN, CDI_4STERN, CDI_5STERN,
    CSN_A, CSN_B, CSN_C, CSI_1STERN, CSI_2STERN, CSI_3STERN, CSI_4STERN, CSI_5STERN,
    CCI_1STERN, CCI_2STERN, CCI_3STERN, CCI_4STERN, CCI_5STERN,
    CAI, REGIONAL, LANDESMEISTERSCHAFT, STAATSMEISTERSCHAFT,
    OESTERREICHISCHE_MEISTERSCHAFT, EUROPAMEISTERSCHAFT, WELTMEISTERSCHAFT,
    OLYMPISCHE_SPIELE, SONSTIGE
}

@Serializable
enum class ErgebnisStatusE {
    NICHT_GESTARTET, GESTARTET, BEENDET, DISQUALIFIZIERT, ZURUECKGEZOGEN,
    AUSGESCHIEDEN, NICHT_KLASSIFIZIERT, ELIMINIERT
}

@Serializable
enum class ZahlungsStatusE {
    OFFEN, BEZAHLT, TEILWEISE_BEZAHLT, UEBERFAELLIG, STORNIERT, RUECKERSTATTET
}

// Administrative enums
@Serializable
enum class DokumentTypE {
    AUSSCHREIBUNG, STARTLISTE, ERGEBNISLISTE, PROTOKOLL, PARCOURSSKIZZE,
    ZEITPLAN, NENNUNGSFORMULAR, RECHNUNG, LIZENZ, PASS, GESUNDHEITSZEUGNIS,
    VERSICHERUNG, HAFTUNGSAUSSCHLUSS, SONSTIGE
}

@Serializable
enum class KommunikationsTypE {
    EMAIL, SMS, BRIEF, TELEFON, FAX, ONLINE_PORTAL, PUSH_NOTIFICATION, SONSTIGE
}

@Serializable
enum class PrioritaetE { NIEDRIG, NORMAL, HOCH, KRITISCH }
