@startuml
title "Service-Interaktion: Nennung wird validiert"

actor Reiter

participant "Nennungs_Context" as Nenn
participant "Veranstaltungs_Context" as Veranst
participant "Lizenzen_und_Qualifikationen_Context" as Lizenz

Reiter -> Nenn : Nennung abgeben für Prüfung "A-Dressur"
activate Nenn

Nenn -> Veranst : anfrage: getPruefungsAnforderungen("A-Dressur")
activate Veranst
Veranst --> Nenn : antwort: {erf. Lizenz: "R1", erf. Alter: "U21"}
deactivate Veranst

Nenn -> Lizenz : anfrage: hatStartberechtigung(Reiter-ID, {erf. Lizenz: "R1", erf. Alter: "U21"})
activate Lizenz
Lizenz --> Nenn : antwort: {status: "OK"}
deactivate Lizenz

Nenn -> Nenn : Nennung speichern (Status: "Angenommen")
Nenn --> Reiter : Bestätigung: Nennung erfolgreich!
deactivate Nenn

@enduml
